/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module \NAND  (
  input A,
  input B,
  output O
);
  assign O = ~ (A & B);
endmodule

module \NOT  (
  input A,
  output O
);
  \NAND  \NAND_i0 (
    .A( A ),
    .B( A ),
    .O( O )
  );
endmodule

module \OR  (
  input A,
  input B,
  output O
);
  wire s0;
  wire s1;
  \NOT  \NOT_i0 (
    .A( B ),
    .O( s1 )
  );
  \NOT  \NOT_i1 (
    .A( A ),
    .O( s0 )
  );
  \NAND  \NAND_i2 (
    .A( s0 ),
    .B( s1 ),
    .O( O )
  );
endmodule

module \AND  (
  input A,
  input B,
  output O
);
  wire s0;
  wire s1;
  \NAND  \NAND_i0 (
    .A( A ),
    .B( B ),
    .O( s0 )
  );
  \NAND  \NAND_i1 (
    .A( B ),
    .B( A ),
    .O( s1 )
  );
  \NAND  \NAND_i2 (
    .A( s0 ),
    .B( s1 ),
    .O( O )
  );
endmodule

module \NOR  (
  input A,
  input B,
  output O
);
  wire s0;
  \OR  \OR_i0 (
    .A( A ),
    .B( B ),
    .O( s0 )
  );
  \NOT  \NOT_i1 (
    .A( s0 ),
    .O( O )
  );
endmodule

module D_latch (
  input D,
  input CLK,
  input R,
  output O
);
  wire O_temp;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  \AND  \AND_i0 (
    .A( D ),
    .B( CLK ),
    .O( s2 )
  );
  \NOT  \NOT_i1 (
    .A( D ),
    .O( s4 )
  );
  \AND  \AND_i2 (
    .A( s4 ),
    .B( CLK ),
    .O( s0 )
  );
  \NOR  \NOR_i3 (
    .A( O_temp ),
    .B( s0 ),
    .O( s1 )
  );
  \NOR  \NOR_i4 (
    .A( s2 ),
    .B( s1 ),
    .O( s3 )
  );
  \OR  \OR_i5 (
    .A( R ),
    .B( s3 ),
    .O( O_temp )
  );
  assign O = O_temp;
endmodule

module flip_flop (
  input D,
  input CLK,
  input R,
  output O
);
  wire s0;
  wire s1;
  D_latch D_latch_i0 (
    .D( D ),
    .CLK( CLK ),
    .R( R ),
    .O( s0 )
  );
  \NOT  \NOT_i1 (
    .A( CLK ),
    .O( s1 )
  );
  D_latch D_latch_i2 (
    .D( s0 ),
    .CLK( s1 ),
    .R( R ),
    .O( O )
  );
endmodule

module AND16 (
  input [15:0] A,
  input [15:0] B,
  output [15:0] O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  assign s0 = A[0];
  assign s3 = A[1];
  assign s6 = A[2];
  assign s9 = A[3];
  assign s12 = A[4];
  assign s15 = A[5];
  assign s18 = A[6];
  assign s21 = A[7];
  assign s24 = A[8];
  assign s27 = A[9];
  assign s30 = A[10];
  assign s33 = A[11];
  assign s36 = A[12];
  assign s39 = A[13];
  assign s42 = A[14];
  assign s45 = A[15];
  assign s1 = B[0];
  assign s4 = B[1];
  assign s7 = B[2];
  assign s10 = B[3];
  assign s13 = B[4];
  assign s16 = B[5];
  assign s19 = B[6];
  assign s22 = B[7];
  assign s25 = B[8];
  assign s28 = B[9];
  assign s31 = B[10];
  assign s34 = B[11];
  assign s37 = B[12];
  assign s40 = B[13];
  assign s43 = B[14];
  assign s46 = B[15];
  \AND  \AND_i0 (
    .A( s0 ),
    .B( s1 ),
    .O( s2 )
  );
  \AND  \AND_i1 (
    .A( s3 ),
    .B( s4 ),
    .O( s5 )
  );
  \AND  \AND_i2 (
    .A( s6 ),
    .B( s7 ),
    .O( s8 )
  );
  \AND  \AND_i3 (
    .A( s9 ),
    .B( s10 ),
    .O( s11 )
  );
  \AND  \AND_i4 (
    .A( s12 ),
    .B( s13 ),
    .O( s14 )
  );
  \AND  \AND_i5 (
    .A( s15 ),
    .B( s16 ),
    .O( s17 )
  );
  \AND  \AND_i6 (
    .A( s18 ),
    .B( s19 ),
    .O( s20 )
  );
  \AND  \AND_i7 (
    .A( s21 ),
    .B( s22 ),
    .O( s23 )
  );
  \AND  \AND_i8 (
    .A( s24 ),
    .B( s25 ),
    .O( s26 )
  );
  \AND  \AND_i9 (
    .A( s27 ),
    .B( s28 ),
    .O( s29 )
  );
  \AND  \AND_i10 (
    .A( s30 ),
    .B( s31 ),
    .O( s32 )
  );
  \AND  \AND_i11 (
    .A( s33 ),
    .B( s34 ),
    .O( s35 )
  );
  \AND  \AND_i12 (
    .A( s36 ),
    .B( s37 ),
    .O( s38 )
  );
  \AND  \AND_i13 (
    .A( s39 ),
    .B( s40 ),
    .O( s41 )
  );
  \AND  \AND_i14 (
    .A( s42 ),
    .B( s43 ),
    .O( s44 )
  );
  \AND  \AND_i15 (
    .A( s45 ),
    .B( s46 ),
    .O( s47 )
  );
  assign O[0] = s2;
  assign O[1] = s5;
  assign O[2] = s8;
  assign O[3] = s11;
  assign O[4] = s14;
  assign O[5] = s17;
  assign O[6] = s20;
  assign O[7] = s23;
  assign O[8] = s26;
  assign O[9] = s29;
  assign O[10] = s32;
  assign O[11] = s35;
  assign O[12] = s38;
  assign O[13] = s41;
  assign O[14] = s44;
  assign O[15] = s47;
endmodule

module NOT16 (
  input [15:0] A,
  output [15:0] O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s4 = A[4];
  assign s5 = A[5];
  assign s6 = A[6];
  assign s7 = A[7];
  assign s8 = A[8];
  assign s9 = A[9];
  assign s10 = A[10];
  assign s11 = A[11];
  assign s12 = A[12];
  assign s13 = A[13];
  assign s14 = A[14];
  assign s15 = A[15];
  \NOT  \NOT_i0 (
    .A( s0 ),
    .O( s16 )
  );
  \NOT  \NOT_i1 (
    .A( s1 ),
    .O( s17 )
  );
  \NOT  \NOT_i2 (
    .A( s2 ),
    .O( s18 )
  );
  \NOT  \NOT_i3 (
    .A( s3 ),
    .O( s19 )
  );
  \NOT  \NOT_i4 (
    .A( s4 ),
    .O( s20 )
  );
  \NOT  \NOT_i5 (
    .A( s5 ),
    .O( s21 )
  );
  \NOT  \NOT_i6 (
    .A( s6 ),
    .O( s22 )
  );
  \NOT  \NOT_i7 (
    .A( s7 ),
    .O( s23 )
  );
  \NOT  \NOT_i8 (
    .A( s8 ),
    .O( s24 )
  );
  \NOT  \NOT_i9 (
    .A( s9 ),
    .O( s25 )
  );
  \NOT  \NOT_i10 (
    .A( s10 ),
    .O( s26 )
  );
  \NOT  \NOT_i11 (
    .A( s11 ),
    .O( s27 )
  );
  \NOT  \NOT_i12 (
    .A( s12 ),
    .O( s28 )
  );
  \NOT  \NOT_i13 (
    .A( s13 ),
    .O( s29 )
  );
  \NOT  \NOT_i14 (
    .A( s14 ),
    .O( s30 )
  );
  \NOT  \NOT_i15 (
    .A( s15 ),
    .O( s31 )
  );
  assign O[0] = s16;
  assign O[1] = s17;
  assign O[2] = s18;
  assign O[3] = s19;
  assign O[4] = s20;
  assign O[5] = s21;
  assign O[6] = s22;
  assign O[7] = s23;
  assign O[8] = s24;
  assign O[9] = s25;
  assign O[10] = s26;
  assign O[11] = s27;
  assign O[12] = s28;
  assign O[13] = s29;
  assign O[14] = s30;
  assign O[15] = s31;
endmodule

module OR16 (
  input [15:0] A,
  input [15:0] B,
  output [15:0] O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s4 = A[4];
  assign s5 = A[5];
  assign s6 = A[6];
  assign s7 = A[7];
  assign s8 = A[8];
  assign s9 = A[9];
  assign s10 = A[10];
  assign s11 = A[11];
  assign s12 = A[12];
  assign s13 = A[13];
  assign s14 = A[14];
  assign s15 = A[15];
  assign s16 = B[0];
  assign s17 = B[1];
  assign s18 = B[2];
  assign s19 = B[3];
  assign s20 = B[4];
  assign s21 = B[5];
  assign s22 = B[6];
  assign s23 = B[7];
  assign s24 = B[8];
  assign s25 = B[9];
  assign s26 = B[10];
  assign s27 = B[11];
  assign s28 = B[12];
  assign s29 = B[13];
  assign s30 = B[14];
  assign s31 = B[15];
  \OR  \OR_i0 (
    .A( s0 ),
    .B( s16 ),
    .O( s32 )
  );
  \OR  \OR_i1 (
    .A( s1 ),
    .B( s17 ),
    .O( s33 )
  );
  \OR  \OR_i2 (
    .A( s2 ),
    .B( s18 ),
    .O( s34 )
  );
  \OR  \OR_i3 (
    .A( s3 ),
    .B( s19 ),
    .O( s35 )
  );
  \OR  \OR_i4 (
    .A( s4 ),
    .B( s20 ),
    .O( s36 )
  );
  \OR  \OR_i5 (
    .A( s5 ),
    .B( s21 ),
    .O( s37 )
  );
  \OR  \OR_i6 (
    .A( s6 ),
    .B( s22 ),
    .O( s38 )
  );
  \OR  \OR_i7 (
    .A( s7 ),
    .B( s23 ),
    .O( s39 )
  );
  \OR  \OR_i8 (
    .A( s8 ),
    .B( s24 ),
    .O( s40 )
  );
  \OR  \OR_i9 (
    .A( s9 ),
    .B( s25 ),
    .O( s41 )
  );
  \OR  \OR_i10 (
    .A( s10 ),
    .B( s26 ),
    .O( s42 )
  );
  \OR  \OR_i11 (
    .A( s11 ),
    .B( s27 ),
    .O( s43 )
  );
  \OR  \OR_i12 (
    .A( s12 ),
    .B( s28 ),
    .O( s44 )
  );
  \OR  \OR_i13 (
    .A( s13 ),
    .B( s29 ),
    .O( s45 )
  );
  \OR  \OR_i14 (
    .A( s14 ),
    .B( s30 ),
    .O( s46 )
  );
  \OR  \OR_i15 (
    .A( s15 ),
    .B( s31 ),
    .O( s47 )
  );
  assign O[0] = s32;
  assign O[1] = s33;
  assign O[2] = s34;
  assign O[3] = s35;
  assign O[4] = s36;
  assign O[5] = s37;
  assign O[6] = s38;
  assign O[7] = s39;
  assign O[8] = s40;
  assign O[9] = s41;
  assign O[10] = s42;
  assign O[11] = s43;
  assign O[12] = s44;
  assign O[13] = s45;
  assign O[14] = s46;
  assign O[15] = s47;
endmodule

module \16bit2_to_1MUX  (
  input [15:0] A,
  input [15:0] B,
  input S,
  output [15:0] O
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  assign s2[0] = S;
  assign s2[1] = S;
  assign s2[2] = S;
  assign s2[3] = S;
  assign s2[4] = S;
  assign s2[5] = S;
  assign s2[6] = S;
  assign s2[7] = S;
  assign s2[8] = S;
  assign s2[9] = S;
  assign s2[10] = S;
  assign s2[11] = S;
  assign s2[12] = S;
  assign s2[13] = S;
  assign s2[14] = S;
  assign s2[15] = S;
  AND16 AND16_i0 (
    .A( s2 ),
    .B( B ),
    .O( s3 )
  );
  NOT16 NOT16_i1 (
    .A( s2 ),
    .O( s0 )
  );
  AND16 AND16_i2 (
    .A( A ),
    .B( s0 ),
    .O( s1 )
  );
  OR16 OR16_i3 (
    .A( s1 ),
    .B( s3 ),
    .O( O )
  );
endmodule

module Register (
  input [15:0] Value,
  input clk,
  input WE,
  input R,
  output [15:0] SV
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire [15:0] s32;
  wire [7:0] s33;
  wire [7:0] s34;
  wire [7:0] s35;
  wire [7:0] s36;
  wire [15:0] SV_temp;
  flip_flop flip_flop_i0 (
    .D( s0 ),
    .CLK( clk ),
    .R( R ),
    .O( s1 )
  );
  flip_flop flip_flop_i1 (
    .D( s2 ),
    .CLK( clk ),
    .R( R ),
    .O( s3 )
  );
  flip_flop flip_flop_i2 (
    .D( s4 ),
    .CLK( clk ),
    .R( R ),
    .O( s5 )
  );
  flip_flop flip_flop_i3 (
    .D( s6 ),
    .CLK( clk ),
    .R( R ),
    .O( s7 )
  );
  flip_flop flip_flop_i4 (
    .D( s8 ),
    .CLK( clk ),
    .R( R ),
    .O( s9 )
  );
  flip_flop flip_flop_i5 (
    .D( s10 ),
    .CLK( clk ),
    .R( R ),
    .O( s11 )
  );
  flip_flop flip_flop_i6 (
    .D( s12 ),
    .CLK( clk ),
    .R( R ),
    .O( s13 )
  );
  flip_flop flip_flop_i7 (
    .D( s14 ),
    .CLK( clk ),
    .R( R ),
    .O( s15 )
  );
  flip_flop flip_flop_i8 (
    .D( s16 ),
    .CLK( clk ),
    .R( R ),
    .O( s17 )
  );
  flip_flop flip_flop_i9 (
    .D( s18 ),
    .CLK( clk ),
    .R( R ),
    .O( s19 )
  );
  flip_flop flip_flop_i10 (
    .D( s20 ),
    .CLK( clk ),
    .R( R ),
    .O( s21 )
  );
  flip_flop flip_flop_i11 (
    .D( s22 ),
    .CLK( clk ),
    .R( R ),
    .O( s23 )
  );
  flip_flop flip_flop_i12 (
    .D( s24 ),
    .CLK( clk ),
    .R( R ),
    .O( s25 )
  );
  flip_flop flip_flop_i13 (
    .D( s26 ),
    .CLK( clk ),
    .R( R ),
    .O( s27 )
  );
  flip_flop flip_flop_i14 (
    .D( s28 ),
    .CLK( clk ),
    .R( R ),
    .O( s29 )
  );
  flip_flop flip_flop_i15 (
    .D( s30 ),
    .CLK( clk ),
    .R( R ),
    .O( s31 )
  );
  \16bit2_to_1MUX  \16bit2_to_1MUX_i16 (
    .A( SV_temp ),
    .B( Value ),
    .S( WE ),
    .O( s32 )
  );
  assign s35[0] = s17;
  assign s35[1] = s19;
  assign s35[2] = s21;
  assign s35[3] = s23;
  assign s35[4] = s25;
  assign s35[5] = s27;
  assign s35[6] = s29;
  assign s35[7] = s31;
  assign s36[0] = s1;
  assign s36[1] = s3;
  assign s36[2] = s5;
  assign s36[3] = s7;
  assign s36[4] = s9;
  assign s36[5] = s11;
  assign s36[6] = s13;
  assign s36[7] = s15;
  assign s33 = s32[7:0];
  assign s34 = s32[15:8];
  assign SV_temp[7:0] = s35;
  assign SV_temp[15:8] = s36;
  assign s16 = s33[0];
  assign s18 = s33[1];
  assign s20 = s33[2];
  assign s22 = s33[3];
  assign s24 = s33[4];
  assign s26 = s33[5];
  assign s28 = s33[6];
  assign s30 = s33[7];
  assign s0 = s34[0];
  assign s2 = s34[1];
  assign s4 = s34[2];
  assign s6 = s34[3];
  assign s8 = s34[4];
  assign s10 = s34[5];
  assign s12 = s34[6];
  assign s14 = s34[7];
  assign SV = SV_temp;
endmodule

module \XOR  (
  input A,
  input B,
  output O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  \NOT  \NOT_i0 (
    .A( A ),
    .O( s0 )
  );
  \NOT  \NOT_i1 (
    .A( B ),
    .O( s2 )
  );
  \AND  \AND_i2 (
    .A( s0 ),
    .B( B ),
    .O( s1 )
  );
  \AND  \AND_i3 (
    .A( A ),
    .B( s2 ),
    .O( s3 )
  );
  \OR  \OR_i4 (
    .A( s1 ),
    .B( s3 ),
    .O( O )
  );
endmodule

module Incrementer (
  input [15:0] A,
  input Cin,
  output [15:0] S
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  assign s0 = A[0];
  assign s2 = A[1];
  assign s4 = A[2];
  assign s6 = A[3];
  assign s8 = A[4];
  assign s10 = A[5];
  assign s12 = A[6];
  assign s14 = A[7];
  assign s16 = A[8];
  assign s18 = A[9];
  assign s20 = A[10];
  assign s22 = A[11];
  assign s24 = A[12];
  assign s26 = A[13];
  assign s28 = A[14];
  assign s30 = A[15];
  \AND  \AND_i0 (
    .A( s0 ),
    .B( Cin ),
    .O( s1 )
  );
  \XOR  \XOR_i1 (
    .A( s0 ),
    .B( Cin ),
    .O( s31 )
  );
  \AND  \AND_i2 (
    .A( s1 ),
    .B( s2 ),
    .O( s3 )
  );
  \XOR  \XOR_i3 (
    .A( s2 ),
    .B( s1 ),
    .O( s32 )
  );
  \AND  \AND_i4 (
    .A( s3 ),
    .B( s4 ),
    .O( s5 )
  );
  \XOR  \XOR_i5 (
    .A( s4 ),
    .B( s3 ),
    .O( s33 )
  );
  \AND  \AND_i6 (
    .A( s5 ),
    .B( s6 ),
    .O( s7 )
  );
  \XOR  \XOR_i7 (
    .A( s6 ),
    .B( s5 ),
    .O( s34 )
  );
  \AND  \AND_i8 (
    .A( s7 ),
    .B( s8 ),
    .O( s9 )
  );
  \XOR  \XOR_i9 (
    .A( s8 ),
    .B( s7 ),
    .O( s35 )
  );
  \AND  \AND_i10 (
    .A( s9 ),
    .B( s10 ),
    .O( s11 )
  );
  \XOR  \XOR_i11 (
    .A( s10 ),
    .B( s9 ),
    .O( s36 )
  );
  \AND  \AND_i12 (
    .A( s11 ),
    .B( s12 ),
    .O( s13 )
  );
  \XOR  \XOR_i13 (
    .A( s12 ),
    .B( s11 ),
    .O( s37 )
  );
  \AND  \AND_i14 (
    .A( s13 ),
    .B( s14 ),
    .O( s15 )
  );
  \XOR  \XOR_i15 (
    .A( s14 ),
    .B( s13 ),
    .O( s38 )
  );
  \AND  \AND_i16 (
    .A( s15 ),
    .B( s16 ),
    .O( s17 )
  );
  \XOR  \XOR_i17 (
    .A( s16 ),
    .B( s15 ),
    .O( s39 )
  );
  \AND  \AND_i18 (
    .A( s17 ),
    .B( s18 ),
    .O( s19 )
  );
  \XOR  \XOR_i19 (
    .A( s18 ),
    .B( s17 ),
    .O( s40 )
  );
  \AND  \AND_i20 (
    .A( s19 ),
    .B( s20 ),
    .O( s21 )
  );
  \XOR  \XOR_i21 (
    .A( s20 ),
    .B( s19 ),
    .O( s41 )
  );
  \AND  \AND_i22 (
    .A( s21 ),
    .B( s22 ),
    .O( s23 )
  );
  \XOR  \XOR_i23 (
    .A( s22 ),
    .B( s21 ),
    .O( s42 )
  );
  \AND  \AND_i24 (
    .A( s23 ),
    .B( s24 ),
    .O( s25 )
  );
  \XOR  \XOR_i25 (
    .A( s24 ),
    .B( s23 ),
    .O( s43 )
  );
  \AND  \AND_i26 (
    .A( s25 ),
    .B( s26 ),
    .O( s27 )
  );
  \XOR  \XOR_i27 (
    .A( s26 ),
    .B( s25 ),
    .O( s44 )
  );
  \AND  \AND_i28 (
    .A( s27 ),
    .B( s28 ),
    .O( s29 )
  );
  \XOR  \XOR_i29 (
    .A( s28 ),
    .B( s27 ),
    .O( s45 )
  );
  \AND  \AND_i30 (
    .A( s29 ),
    .B( s30 )
  );
  \XOR  \XOR_i31 (
    .A( s30 ),
    .B( s29 ),
    .O( s46 )
  );
  assign S[0] = s31;
  assign S[1] = s32;
  assign S[2] = s33;
  assign S[3] = s34;
  assign S[4] = s35;
  assign S[5] = s36;
  assign S[6] = s37;
  assign S[7] = s38;
  assign S[8] = s39;
  assign S[9] = s40;
  assign S[10] = s41;
  assign S[11] = s42;
  assign S[12] = s43;
  assign S[13] = s44;
  assign S[14] = s45;
  assign S[15] = s46;
endmodule

module Program_Counter (
  input [15:0] JMP,
  input JE,
  input clk,
  input R,
  input WE,
  output [15:0] O
);
  wire [15:0] s0;
  wire [15:0] O_temp;
  wire [15:0] s1;
  Register Register_i0 (
    .Value( s0 ),
    .clk( clk ),
    .WE( WE ),
    .R( R ),
    .SV( O_temp )
  );
  \16bit2_to_1MUX  \16bit2_to_1MUX_i1 (
    .A( s1 ),
    .B( JMP ),
    .S( JE ),
    .O( s0 )
  );
  Incrementer Incrementer_i2 (
    .A( O_temp ),
    .Cin( 1'b1 ),
    .S( s1 )
  );
  assign O = O_temp;
endmodule

module Instruction_reader (
  input R,
  input clk,
  input [15:0] JMP_ADDR,
  input JMPE,
  input WE,
  input [15:0] Data_in,
  input STR,
  input [15:0] STR_ADDR,
  input [15:0] INSTR_IN,
  output [3:0] OP,
  output [3:0] RA,
  output [3:0] RB,
  output [3:0] RD,
  output [15:0] PC_OUT
);
  wire [15:0] s0;
  Register Register_i0 (
    .Value( INSTR_IN ),
    .clk( clk ),
    .WE( WE ),
    .R( R ),
    .SV( s0 )
  );
  Program_Counter Program_Counter_i1 (
    .JMP( JMP_ADDR ),
    .JE( JMPE ),
    .clk( clk ),
    .R( R ),
    .WE( WE ),
    .O( PC_OUT )
  );
  assign RB = s0[3:0];
  assign RA = s0[7:4];
  assign RD = s0[11:8];
  assign OP = s0[15:12];
endmodule

module \3_to_8_decoder  (
  input [2:0] chs,
  input W,
  output \000 ,
  output \001 ,
  output \010 ,
  output \011 ,
  output \100 ,
  output \101 ,
  output \110 ,
  output \111 
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  assign s0 = chs[0];
  assign s1 = chs[1];
  assign s2 = chs[2];
  \NOT  \NOT_i0 (
    .A( s0 ),
    .O( s3 )
  );
  \NOT  \NOT_i1 (
    .A( s1 ),
    .O( s6 )
  );
  \NOT  \NOT_i2 (
    .A( s2 ),
    .O( s4 )
  );
  \NOT  \NOT_i3 (
    .A( s1 ),
    .O( s10 )
  );
  \NOT  \NOT_i4 (
    .A( s2 ),
    .O( s8 )
  );
  \NOT  \NOT_i5 (
    .A( s2 ),
    .O( s13 )
  );
  \NOT  \NOT_i6 (
    .A( s0 ),
    .O( s12 )
  );
  \NOT  \NOT_i7 (
    .A( s2 ),
    .O( s16 )
  );
  \NOT  \NOT_i8 (
    .A( s1 ),
    .O( s21 )
  );
  \NOT  \NOT_i9 (
    .A( s0 ),
    .O( s19 )
  );
  \AND  \AND_i10 (
    .A( s0 ),
    .B( s2 ),
    .O( s23 )
  );
  \NOT  \NOT_i11 (
    .A( s1 ),
    .O( s24 )
  );
  \NOT  \NOT_i12 (
    .A( s0 ),
    .O( s26 )
  );
  \AND  \AND_i13 (
    .A( s0 ),
    .B( s2 ),
    .O( s29 )
  );
  \AND  \AND_i14 (
    .A( s3 ),
    .B( s4 ),
    .O( s5 )
  );
  \AND  \AND_i15 (
    .A( s0 ),
    .B( s8 ),
    .O( s9 )
  );
  \AND  \AND_i16 (
    .A( s12 ),
    .B( s13 ),
    .O( s14 )
  );
  \AND  \AND_i17 (
    .A( s0 ),
    .B( s16 ),
    .O( s17 )
  );
  \AND  \AND_i18 (
    .A( s19 ),
    .B( s2 ),
    .O( s20 )
  );
  \AND  \AND_i19 (
    .A( s23 ),
    .B( s24 ),
    .O( s25 )
  );
  \AND  \AND_i20 (
    .A( s26 ),
    .B( s2 ),
    .O( s27 )
  );
  \AND  \AND_i21 (
    .A( s29 ),
    .B( s1 ),
    .O( s30 )
  );
  \AND  \AND_i22 (
    .A( s5 ),
    .B( s6 ),
    .O( s7 )
  );
  \AND  \AND_i23 (
    .A( s9 ),
    .B( s10 ),
    .O( s11 )
  );
  \AND  \AND_i24 (
    .A( s14 ),
    .B( s1 ),
    .O( s15 )
  );
  \AND  \AND_i25 (
    .A( s17 ),
    .B( s1 ),
    .O( s18 )
  );
  \AND  \AND_i26 (
    .A( s20 ),
    .B( s21 ),
    .O( s22 )
  );
  \AND  \AND_i27 (
    .A( s27 ),
    .B( s1 ),
    .O( s28 )
  );
  \AND  \AND_i28 (
    .A( s25 ),
    .B( W ),
    .O( \101  )
  );
  \AND  \AND_i29 (
    .A( s30 ),
    .B( W ),
    .O( \111  )
  );
  \AND  \AND_i30 (
    .A( s7 ),
    .B( W ),
    .O( \000  )
  );
  \AND  \AND_i31 (
    .A( s11 ),
    .B( W ),
    .O( \001  )
  );
  \AND  \AND_i32 (
    .A( s15 ),
    .B( W ),
    .O( \010  )
  );
  \AND  \AND_i33 (
    .A( s18 ),
    .B( W ),
    .O( \011  )
  );
  \AND  \AND_i34 (
    .A( s22 ),
    .B( W ),
    .O( \100  )
  );
  \AND  \AND_i35 (
    .A( s28 ),
    .B( W ),
    .O( \110  )
  );
endmodule

module \4_to_16_decoder  (
  input [3:0] sel,
  input W,
  output [15:0] OUT
);
  wire [2:0] s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  assign s0 = sel[2:0];
  assign s19 = sel[3];
  \NOT  \NOT_i0 (
    .A( s19 ),
    .O( s20 )
  );
  \AND  \AND_i1 (
    .A( W ),
    .B( s19 ),
    .O( s1 )
  );
  // HIGH
  \3_to_8_decoder  \3_to_8_decoder_i2 (
    .chs( s0 ),
    .W( s1 ),
    .\000 ( s2 ),
    .\001 ( s3 ),
    .\010 ( s4 ),
    .\011 ( s5 ),
    .\100 ( s6 ),
    .\101 ( s7 ),
    .\110 ( s8 ),
    .\111 ( s9 )
  );
  \AND  \AND_i3 (
    .A( W ),
    .B( s20 ),
    .O( s10 )
  );
  // LOW
  \3_to_8_decoder  \3_to_8_decoder_i4 (
    .chs( s0 ),
    .W( s10 ),
    .\000 ( s11 ),
    .\001 ( s12 ),
    .\010 ( s13 ),
    .\011 ( s14 ),
    .\100 ( s15 ),
    .\101 ( s16 ),
    .\110 ( s17 ),
    .\111 ( s18 )
  );
  assign OUT[0] = s11;
  assign OUT[1] = s12;
  assign OUT[2] = s13;
  assign OUT[3] = s14;
  assign OUT[4] = s15;
  assign OUT[5] = s16;
  assign OUT[6] = s17;
  assign OUT[7] = s18;
  assign OUT[8] = s2;
  assign OUT[9] = s3;
  assign OUT[10] = s4;
  assign OUT[11] = s5;
  assign OUT[12] = s6;
  assign OUT[13] = s7;
  assign OUT[14] = s8;
  assign OUT[15] = s9;
endmodule

module control (
  input [3:0] OP,
  output [12:0] OUT
);
  wire [15:0] s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  \4_to_16_decoder  \4_to_16_decoder_i0 (
    .sel( OP ),
    .W( 1'b1 ),
    .OUT( s0 )
  );
  assign s1 = s0[1];
  assign s2 = s0[2];
  assign s3 = s0[3];
  assign s4 = s0[4];
  assign s5 = s0[5];
  assign s6 = s0[6];
  assign s7 = s0[7];
  assign s8 = s0[9];
  assign s9 = s0[10];
  assign s10 = s0[12];
  assign s11 = s0[13];
  assign s12 = s0[14];
  assign OUT[0] = (s1 | s2 | s3 | s4 | s5 | s6 | s7 | s8 | s9);
  assign OUT[1] = (s1 | s2 | s4 | s6);
  assign OUT[2] = (s3 | s4);
  assign OUT[3] = (s5 | s6);
  assign OUT[4] = s2;
  assign OUT[5] = (s7 | s8);
  assign OUT[6] = (s8 | s9);
  assign OUT[7] = s0[8];
  assign OUT[8] = (s0[11] | s10 | s11 | s12);
  assign OUT[9] = (s10 | s12);
  assign OUT[10] = (s11 | s12);
  assign OUT[11] = (s1 | s2);
  assign OUT[12] = s0[15];
endmodule

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module XOR16 (
  input [15:0] A,
  input [15:0] B,
  output [15:0] O
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s4 = A[4];
  assign s5 = A[5];
  assign s6 = A[6];
  assign s7 = A[7];
  assign s8 = A[8];
  assign s9 = A[9];
  assign s10 = A[10];
  assign s11 = A[11];
  assign s12 = A[12];
  assign s13 = A[13];
  assign s14 = A[14];
  assign s15 = A[15];
  assign s16 = B[0];
  assign s17 = B[1];
  assign s18 = B[2];
  assign s19 = B[3];
  assign s20 = B[4];
  assign s21 = B[5];
  assign s22 = B[6];
  assign s23 = B[7];
  assign s24 = B[8];
  assign s25 = B[9];
  assign s26 = B[10];
  assign s27 = B[11];
  assign s28 = B[12];
  assign s29 = B[13];
  assign s30 = B[14];
  assign s31 = B[15];
  \XOR  \XOR_i0 (
    .A( s0 ),
    .B( s16 ),
    .O( s32 )
  );
  \XOR  \XOR_i1 (
    .A( s1 ),
    .B( s17 ),
    .O( s33 )
  );
  \XOR  \XOR_i2 (
    .A( s2 ),
    .B( s18 ),
    .O( s34 )
  );
  \XOR  \XOR_i3 (
    .A( s3 ),
    .B( s19 ),
    .O( s35 )
  );
  \XOR  \XOR_i4 (
    .A( s4 ),
    .B( s20 ),
    .O( s36 )
  );
  \XOR  \XOR_i5 (
    .A( s5 ),
    .B( s21 ),
    .O( s37 )
  );
  \XOR  \XOR_i6 (
    .A( s6 ),
    .B( s22 ),
    .O( s38 )
  );
  \XOR  \XOR_i7 (
    .A( s7 ),
    .B( s23 ),
    .O( s39 )
  );
  \XOR  \XOR_i8 (
    .A( s8 ),
    .B( s24 ),
    .O( s40 )
  );
  \XOR  \XOR_i9 (
    .A( s9 ),
    .B( s25 ),
    .O( s41 )
  );
  \XOR  \XOR_i10 (
    .A( s10 ),
    .B( s26 ),
    .O( s42 )
  );
  \XOR  \XOR_i11 (
    .A( s11 ),
    .B( s27 ),
    .O( s43 )
  );
  \XOR  \XOR_i12 (
    .A( s12 ),
    .B( s28 ),
    .O( s44 )
  );
  \XOR  \XOR_i13 (
    .A( s13 ),
    .B( s29 ),
    .O( s45 )
  );
  \XOR  \XOR_i14 (
    .A( s14 ),
    .B( s30 ),
    .O( s46 )
  );
  \XOR  \XOR_i15 (
    .A( s15 ),
    .B( s31 ),
    .O( s47 )
  );
  assign O[0] = s32;
  assign O[1] = s33;
  assign O[2] = s34;
  assign O[3] = s35;
  assign O[4] = s36;
  assign O[5] = s37;
  assign O[6] = s38;
  assign O[7] = s39;
  assign O[8] = s40;
  assign O[9] = s41;
  assign O[10] = s42;
  assign O[11] = s43;
  assign O[12] = s44;
  assign O[13] = s45;
  assign O[14] = s46;
  assign O[15] = s47;
endmodule

module Parallel_adder (
  input A0,
  input A1,
  input A2,
  input A3,
  input B0,
  input B1,
  input B2,
  input B3,
  input Cin,
  output S0,
  output S1,
  output S2,
  output S3,
  output C4,
  output C3
);
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire C3_temp;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  \XOR  \XOR_i0 (
    .A( A0 ),
    .B( B0 ),
    .O( s4 )
  );
  \XOR  \XOR_i1 (
    .A( A1 ),
    .B( B1 ),
    .O( s5 )
  );
  \XOR  \XOR_i2 (
    .A( A2 ),
    .B( B2 ),
    .O( s6 )
  );
  \XOR  \XOR_i3 (
    .A( A3 ),
    .B( B3 ),
    .O( s7 )
  );
  \AND  \AND_i4 (
    .A( A0 ),
    .B( B0 ),
    .O( s8 )
  );
  \AND  \AND_i5 (
    .A( A1 ),
    .B( B1 ),
    .O( s9 )
  );
  \AND  \AND_i6 (
    .A( A2 ),
    .B( B2 ),
    .O( s10 )
  );
  \AND  \AND_i7 (
    .A( A3 ),
    .B( B3 ),
    .O( s11 )
  );
  \AND  \AND_i8 (
    .A( s4 ),
    .B( Cin ),
    .O( s12 )
  );
  \AND  \AND_i9 (
    .A( s8 ),
    .B( s5 ),
    .O( s14 )
  );
  \AND  \AND_i10 (
    .A( s4 ),
    .B( s5 ),
    .O( s15 )
  );
  \AND  \AND_i11 (
    .A( s4 ),
    .B( s5 ),
    .O( s24 )
  );
  \AND  \AND_i12 (
    .A( s6 ),
    .B( Cin ),
    .O( s25 )
  );
  \AND  \AND_i13 (
    .A( s6 ),
    .B( s5 ),
    .O( s26 )
  );
  \AND  \AND_i14 (
    .A( s6 ),
    .B( s9 ),
    .O( s20 )
  );
  \AND  \AND_i15 (
    .A( s4 ),
    .B( s5 ),
    .O( s27 )
  );
  \AND  \AND_i16 (
    .A( s6 ),
    .B( s7 ),
    .O( s28 )
  );
  \AND  \AND_i17 (
    .A( s5 ),
    .B( s6 ),
    .O( s31 )
  );
  \AND  \AND_i18 (
    .A( s7 ),
    .B( s8 ),
    .O( s32 )
  );
  \AND  \AND_i19 (
    .A( s6 ),
    .B( s7 ),
    .O( s34 )
  );
  \AND  \AND_i20 (
    .A( s10 ),
    .B( s7 ),
    .O( s36 )
  );
  \XOR  \XOR_i21 (
    .A( s4 ),
    .B( Cin ),
    .O( S0 )
  );
  \OR  \OR_i22 (
    .A( s12 ),
    .B( s8 ),
    .O( s13 )
  );
  \AND  \AND_i23 (
    .A( s15 ),
    .B( Cin ),
    .O( s16 )
  );
  \AND  \AND_i24 (
    .A( s24 ),
    .B( s25 ),
    .O( s22 )
  );
  \AND  \AND_i25 (
    .A( s26 ),
    .B( s8 ),
    .O( s23 )
  );
  \AND  \AND_i26 (
    .A( s27 ),
    .B( s28 ),
    .O( s29 )
  );
  \AND  \AND_i27 (
    .A( s31 ),
    .B( s32 ),
    .O( s33 )
  );
  \AND  \AND_i28 (
    .A( s34 ),
    .B( s9 ),
    .O( s35 )
  );
  \OR  \OR_i29 (
    .A( s36 ),
    .B( s11 ),
    .O( s38 )
  );
  \OR  \OR_i30 (
    .A( s14 ),
    .B( s16 ),
    .O( s17 )
  );
  \OR  \OR_i31 (
    .A( s22 ),
    .B( s23 ),
    .O( s19 )
  );
  \AND  \AND_i32 (
    .A( s29 ),
    .B( Cin ),
    .O( s30 )
  );
  \XOR  \XOR_i33 (
    .A( s5 ),
    .B( s13 ),
    .O( S1 )
  );
  \OR  \OR_i34 (
    .A( s9 ),
    .B( s17 ),
    .O( s18 )
  );
  \OR  \OR_i35 (
    .A( s19 ),
    .B( s20 ),
    .O( s21 )
  );
  \OR  \OR_i36 (
    .A( s30 ),
    .B( s33 ),
    .O( s37 )
  );
  \OR  \OR_i37 (
    .A( s21 ),
    .B( s10 ),
    .O( C3_temp )
  );
  \OR  \OR_i38 (
    .A( s37 ),
    .B( s35 ),
    .O( s39 )
  );
  \XOR  \XOR_i39 (
    .A( s6 ),
    .B( s18 ),
    .O( S2 )
  );
  \OR  \OR_i40 (
    .A( s39 ),
    .B( s38 ),
    .O( C4 )
  );
  \XOR  \XOR_i41 (
    .A( s7 ),
    .B( C3_temp ),
    .O( S3 )
  );
  assign C3 = C3_temp;
endmodule

module Full_add_sub (
  input Cin,
  input [15:0] A,
  input [15:0] B,
  output [15:0] S,
  output N,
  output C,
  output V,
  output Z
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire N_temp;
  wire C_temp;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire [3:0] s67;
  wire [3:0] s68;
  wire [3:0] s69;
  wire [3:0] s70;
  wire [15:0] S_temp;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  assign s0 = A[0];
  assign s1 = A[1];
  assign s2 = A[2];
  assign s3 = A[3];
  assign s27 = A[4];
  assign s28 = A[5];
  assign s29 = A[6];
  assign s30 = A[7];
  assign s13 = A[8];
  assign s14 = A[9];
  assign s15 = A[10];
  assign s16 = A[11];
  assign s39 = A[12];
  assign s40 = A[13];
  assign s41 = A[14];
  assign s42 = A[15];
  assign s51 = B[0];
  assign s52 = B[1];
  assign s53 = B[2];
  assign s54 = B[3];
  assign s55 = B[4];
  assign s56 = B[5];
  assign s57 = B[6];
  assign s58 = B[7];
  assign s59 = B[8];
  assign s60 = B[9];
  assign s61 = B[10];
  assign s62 = B[11];
  assign s63 = B[12];
  assign s64 = B[13];
  assign s65 = B[14];
  assign s66 = B[15];
  \XOR  \XOR_i0 (
    .A( s51 ),
    .B( Cin ),
    .O( s4 )
  );
  \XOR  \XOR_i1 (
    .A( s52 ),
    .B( Cin ),
    .O( s5 )
  );
  \XOR  \XOR_i2 (
    .A( s53 ),
    .B( Cin ),
    .O( s6 )
  );
  \XOR  \XOR_i3 (
    .A( s54 ),
    .B( Cin ),
    .O( s7 )
  );
  \XOR  \XOR_i4 (
    .A( s55 ),
    .B( Cin ),
    .O( s31 )
  );
  \XOR  \XOR_i5 (
    .A( s56 ),
    .B( Cin ),
    .O( s32 )
  );
  \XOR  \XOR_i6 (
    .A( s57 ),
    .B( Cin ),
    .O( s33 )
  );
  \XOR  \XOR_i7 (
    .A( s58 ),
    .B( Cin ),
    .O( s34 )
  );
  \XOR  \XOR_i8 (
    .A( s59 ),
    .B( Cin ),
    .O( s17 )
  );
  \XOR  \XOR_i9 (
    .A( s60 ),
    .B( Cin ),
    .O( s18 )
  );
  \XOR  \XOR_i10 (
    .A( s61 ),
    .B( Cin ),
    .O( s19 )
  );
  \XOR  \XOR_i11 (
    .A( s62 ),
    .B( Cin ),
    .O( s20 )
  );
  \XOR  \XOR_i12 (
    .A( s63 ),
    .B( Cin ),
    .O( s43 )
  );
  \XOR  \XOR_i13 (
    .A( s64 ),
    .B( Cin ),
    .O( s44 )
  );
  \XOR  \XOR_i14 (
    .A( s65 ),
    .B( Cin ),
    .O( s45 )
  );
  \XOR  \XOR_i15 (
    .A( s66 ),
    .B( Cin ),
    .O( s46 )
  );
  Parallel_adder Parallel_adder_i16 (
    .A0( s0 ),
    .A1( s1 ),
    .A2( s2 ),
    .A3( s3 ),
    .B0( s4 ),
    .B1( s5 ),
    .B2( s6 ),
    .B3( s7 ),
    .Cin( Cin ),
    .S0( s8 ),
    .S1( s9 ),
    .S2( s10 ),
    .S3( s11 ),
    .C4( s12 )
  );
  Parallel_adder Parallel_adder_i17 (
    .A0( s27 ),
    .A1( s28 ),
    .A2( s29 ),
    .A3( s30 ),
    .B0( s31 ),
    .B1( s32 ),
    .B2( s33 ),
    .B3( s34 ),
    .Cin( s12 ),
    .S0( s35 ),
    .S1( s36 ),
    .S2( s37 ),
    .S3( s38 ),
    .C4( s21 )
  );
  assign s67[0] = s8;
  assign s67[1] = s9;
  assign s67[2] = s10;
  assign s67[3] = s11;
  Parallel_adder Parallel_adder_i18 (
    .A0( s13 ),
    .A1( s14 ),
    .A2( s15 ),
    .A3( s16 ),
    .B0( s17 ),
    .B1( s18 ),
    .B2( s19 ),
    .B3( s20 ),
    .Cin( s21 ),
    .S0( s22 ),
    .S1( s23 ),
    .S2( s24 ),
    .S3( s25 ),
    .C4( s26 )
  );
  assign s68[0] = s35;
  assign s68[1] = s36;
  assign s68[2] = s37;
  assign s68[3] = s38;
  Parallel_adder Parallel_adder_i19 (
    .A0( s39 ),
    .A1( s40 ),
    .A2( s41 ),
    .A3( s42 ),
    .B0( s43 ),
    .B1( s44 ),
    .B2( s45 ),
    .B3( s46 ),
    .Cin( s26 ),
    .S0( s47 ),
    .S1( s48 ),
    .S2( s49 ),
    .S3( N_temp ),
    .C4( C_temp ),
    .C3( s50 )
  );
  assign s69[0] = s22;
  assign s69[1] = s23;
  assign s69[2] = s24;
  assign s69[3] = s25;
  assign s70[0] = s47;
  assign s70[1] = s48;
  assign s70[2] = s49;
  assign s70[3] = N_temp;
  \XOR  \XOR_i20 (
    .A( C_temp ),
    .B( s50 ),
    .O( V )
  );
  assign S_temp[3:0] = s67;
  assign S_temp[7:4] = s68;
  assign S_temp[11:8] = s69;
  assign S_temp[15:12] = s70;
  assign s71 = S_temp[0];
  assign s72 = S_temp[1];
  assign s73 = S_temp[2];
  assign s74 = S_temp[3];
  assign s75 = S_temp[4];
  assign s76 = S_temp[5];
  assign s77 = S_temp[6];
  assign s78 = S_temp[7];
  assign s79 = S_temp[8];
  assign s80 = S_temp[9];
  assign s81 = S_temp[10];
  assign s82 = S_temp[11];
  assign s83 = S_temp[12];
  assign s84 = S_temp[13];
  assign s85 = S_temp[14];
  assign s86 = S_temp[15];
  \OR  \OR_i21 (
    .A( s71 ),
    .B( s72 ),
    .O( s87 )
  );
  \OR  \OR_i22 (
    .A( s73 ),
    .B( s74 ),
    .O( s88 )
  );
  \OR  \OR_i23 (
    .A( s75 ),
    .B( s76 ),
    .O( s89 )
  );
  \OR  \OR_i24 (
    .A( s77 ),
    .B( s78 ),
    .O( s90 )
  );
  \OR  \OR_i25 (
    .A( s79 ),
    .B( s80 ),
    .O( s91 )
  );
  \OR  \OR_i26 (
    .A( s81 ),
    .B( s82 ),
    .O( s92 )
  );
  \OR  \OR_i27 (
    .A( s83 ),
    .B( s84 ),
    .O( s93 )
  );
  \OR  \OR_i28 (
    .A( s85 ),
    .B( s86 ),
    .O( s94 )
  );
  \OR  \OR_i29 (
    .A( s87 ),
    .B( s88 ),
    .O( s95 )
  );
  \OR  \OR_i30 (
    .A( s89 ),
    .B( s90 ),
    .O( s99 )
  );
  \OR  \OR_i31 (
    .A( s91 ),
    .B( s92 ),
    .O( s96 )
  );
  \OR  \OR_i32 (
    .A( s93 ),
    .B( s94 ),
    .O( s97 )
  );
  \OR  \OR_i33 (
    .A( s96 ),
    .B( s97 ),
    .O( s98 )
  );
  \OR  \OR_i34 (
    .A( s95 ),
    .B( s99 ),
    .O( s100 )
  );
  \OR  \OR_i35 (
    .A( s100 ),
    .B( s98 ),
    .O( s101 )
  );
  \NOT  \NOT_i36 (
    .A( s101 ),
    .O( Z )
  );
  assign S = S_temp;
  assign N = N_temp;
  assign C = C_temp;
endmodule

module \2_to_1_MUX  (
  input A,
  input B,
  input S,
  output O
);
  wire s0;
  wire s1;
  wire s2;
  \AND  \AND_i0 (
    .A( S ),
    .B( B ),
    .O( s0 )
  );
  \NOT  \NOT_i1 (
    .A( S ),
    .O( s1 )
  );
  \AND  \AND_i2 (
    .A( A ),
    .B( s1 ),
    .O( s2 )
  );
  \OR  \OR_i3 (
    .A( s2 ),
    .B( s0 ),
    .O( O )
  );
endmodule

module \4_to_1_MUX  (
  input S1,
  input S2,
  input A1,
  input B1,
  input A2,
  input B2,
  output O
);
  wire s0;
  wire s3;
  \2_to_1_MUX  \2_to_1_MUX_i0 (
    .A( A1 ),
    .B( B1 ),
    .S( S1 ),
    .O( s0 )
  );
  \2_to_1_MUX  \2_to_1_MUX_i1 (
    .A( A2 ),
    .B( B2 ),
    .S( S1 ),
    .O( s3 )
  );
  \2_to_1_MUX  \2_to_1_MUX_i2 (
    .A( s0 ),
    .B( s3 ),
    .S( S2 ),
    .O( O )
  );
endmodule

module \8_to_1_MUX  (
  input [2:0] S,
  input [7:0] \Input ,
  output OUT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  assign s0 = S[0];
  assign s1 = S[1];
  assign s12 = S[2];
  assign s2 = \Input [0];
  assign s3 = \Input [1];
  assign s4 = \Input [2];
  assign s5 = \Input [3];
  assign s7 = \Input [4];
  assign s8 = \Input [5];
  assign s9 = \Input [6];
  assign s10 = \Input [7];
  \4_to_1_MUX  \4_to_1_MUX_i0 (
    .S1( s0 ),
    .S2( s1 ),
    .A1( s2 ),
    .B1( s3 ),
    .A2( s4 ),
    .B2( s5 ),
    .O( s6 )
  );
  \4_to_1_MUX  \4_to_1_MUX_i1 (
    .S1( s0 ),
    .S2( s1 ),
    .A1( s7 ),
    .B1( s8 ),
    .A2( s9 ),
    .B2( s10 ),
    .O( s11 )
  );
  \2_to_1_MUX  \2_to_1_MUX_i2 (
    .A( s6 ),
    .B( s11 ),
    .S( s12 ),
    .O( OUT )
  );
endmodule

module \16bit_8_to_1_MUX  (
  input [2:0] OP,
  input [15:0] AD,
  input [15:0] SB,
  input [15:0] ND,
  input [15:0] \OR ,
  input [15:0] XR,
  input [15:0] NT,
  input [15:0] SP,
  input [15:0] SP2,
  output [15:0] OT
);
  wire [7:0] s0;
  wire s1;
  wire [7:0] s2;
  wire s3;
  wire [7:0] s4;
  wire s5;
  wire [7:0] s6;
  wire s7;
  wire [7:0] s8;
  wire s9;
  wire [7:0] s10;
  wire s11;
  wire [7:0] s12;
  wire s13;
  wire [7:0] s14;
  wire s15;
  wire [7:0] s16;
  wire s17;
  wire [7:0] s18;
  wire s19;
  wire [7:0] s20;
  wire s21;
  wire [7:0] s22;
  wire s23;
  wire [7:0] s24;
  wire s25;
  wire [7:0] s26;
  wire s27;
  wire [7:0] s28;
  wire s29;
  wire [7:0] s30;
  wire s31;
  assign s0[0] = AD[0];
  assign s0[1] = SB[0];
  assign s0[2] = ND[0];
  assign s0[3] = \OR [0];
  assign s0[4] = XR[0];
  assign s0[5] = NT[0];
  assign s0[6] = SP[0];
  assign s0[7] = SP2[0];
  assign s2[0] = AD[1];
  assign s2[1] = SB[1];
  assign s2[2] = ND[1];
  assign s2[3] = \OR [1];
  assign s2[4] = XR[1];
  assign s2[5] = NT[1];
  assign s2[6] = SP[1];
  assign s2[7] = SP2[1];
  assign s4[0] = AD[2];
  assign s4[1] = SB[2];
  assign s4[2] = ND[2];
  assign s4[3] = \OR [2];
  assign s4[4] = XR[2];
  assign s4[5] = NT[2];
  assign s4[6] = SP[2];
  assign s4[7] = SP2[2];
  assign s6[0] = AD[3];
  assign s6[1] = SB[3];
  assign s6[2] = ND[3];
  assign s6[3] = \OR [3];
  assign s6[4] = XR[3];
  assign s6[5] = NT[3];
  assign s6[6] = SP[3];
  assign s6[7] = SP2[3];
  assign s8[0] = AD[4];
  assign s8[1] = SB[4];
  assign s8[2] = ND[4];
  assign s8[3] = \OR [4];
  assign s8[4] = XR[4];
  assign s8[5] = NT[4];
  assign s8[6] = SP[4];
  assign s8[7] = SP2[4];
  assign s10[0] = AD[5];
  assign s10[1] = SB[5];
  assign s10[2] = ND[5];
  assign s10[3] = \OR [5];
  assign s10[4] = XR[5];
  assign s10[5] = NT[5];
  assign s10[6] = SP[5];
  assign s10[7] = SP2[5];
  assign s12[0] = AD[6];
  assign s12[1] = SB[6];
  assign s12[2] = ND[6];
  assign s12[3] = \OR [6];
  assign s12[4] = XR[6];
  assign s12[5] = NT[6];
  assign s12[6] = SP[6];
  assign s12[7] = SP2[6];
  assign s14[0] = AD[7];
  assign s14[1] = SB[7];
  assign s14[2] = ND[7];
  assign s14[3] = \OR [7];
  assign s14[4] = XR[7];
  assign s14[5] = NT[7];
  assign s14[6] = SP[7];
  assign s14[7] = SP2[7];
  assign s16[0] = AD[8];
  assign s16[1] = SB[8];
  assign s16[2] = ND[8];
  assign s16[3] = \OR [8];
  assign s16[4] = XR[8];
  assign s16[5] = NT[8];
  assign s16[6] = SP[8];
  assign s16[7] = SP2[8];
  assign s18[0] = AD[9];
  assign s18[1] = SB[9];
  assign s18[2] = ND[9];
  assign s18[3] = \OR [9];
  assign s18[4] = XR[9];
  assign s18[5] = NT[9];
  assign s18[6] = SP[9];
  assign s18[7] = SP2[9];
  assign s20[0] = AD[10];
  assign s20[1] = SB[10];
  assign s20[2] = ND[10];
  assign s20[3] = \OR [10];
  assign s20[4] = XR[10];
  assign s20[5] = NT[10];
  assign s20[6] = SP[10];
  assign s20[7] = SP2[10];
  assign s22[0] = AD[11];
  assign s22[1] = SB[11];
  assign s22[2] = ND[11];
  assign s22[3] = \OR [11];
  assign s22[4] = XR[11];
  assign s22[5] = NT[11];
  assign s22[6] = SP[11];
  assign s22[7] = SP2[11];
  assign s24[0] = AD[12];
  assign s24[1] = SB[12];
  assign s24[2] = ND[12];
  assign s24[3] = \OR [12];
  assign s24[4] = XR[12];
  assign s24[5] = NT[12];
  assign s24[6] = SP[12];
  assign s24[7] = SP2[12];
  assign s26[0] = AD[13];
  assign s26[1] = SB[13];
  assign s26[2] = ND[13];
  assign s26[3] = \OR [13];
  assign s26[4] = XR[13];
  assign s26[5] = NT[13];
  assign s26[6] = SP[13];
  assign s26[7] = SP2[13];
  assign s28[0] = AD[14];
  assign s28[1] = SB[14];
  assign s28[2] = ND[14];
  assign s28[3] = \OR [14];
  assign s28[4] = XR[14];
  assign s28[5] = NT[14];
  assign s28[6] = SP[14];
  assign s28[7] = SP2[14];
  assign s30[0] = AD[15];
  assign s30[1] = SB[15];
  assign s30[2] = ND[15];
  assign s30[3] = \OR [15];
  assign s30[4] = XR[15];
  assign s30[5] = NT[15];
  assign s30[6] = SP[15];
  assign s30[7] = SP2[15];
  \8_to_1_MUX  \8_to_1_MUX_i0 (
    .S( OP ),
    .\Input ( s0 ),
    .OUT( s1 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i1 (
    .S( OP ),
    .\Input ( s2 ),
    .OUT( s3 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i2 (
    .S( OP ),
    .\Input ( s4 ),
    .OUT( s5 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i3 (
    .S( OP ),
    .\Input ( s6 ),
    .OUT( s7 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i4 (
    .S( OP ),
    .\Input ( s8 ),
    .OUT( s9 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i5 (
    .S( OP ),
    .\Input ( s10 ),
    .OUT( s11 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i6 (
    .S( OP ),
    .\Input ( s12 ),
    .OUT( s13 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i7 (
    .S( OP ),
    .\Input ( s14 ),
    .OUT( s15 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i8 (
    .S( OP ),
    .\Input ( s16 ),
    .OUT( s17 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i9 (
    .S( OP ),
    .\Input ( s18 ),
    .OUT( s19 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i10 (
    .S( OP ),
    .\Input ( s20 ),
    .OUT( s21 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i11 (
    .S( OP ),
    .\Input ( s22 ),
    .OUT( s23 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i12 (
    .S( OP ),
    .\Input ( s24 ),
    .OUT( s25 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i13 (
    .S( OP ),
    .\Input ( s26 ),
    .OUT( s27 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i14 (
    .S( OP ),
    .\Input ( s28 ),
    .OUT( s29 )
  );
  \8_to_1_MUX  \8_to_1_MUX_i15 (
    .S( OP ),
    .\Input ( s30 ),
    .OUT( s31 )
  );
  assign OT[0] = s1;
  assign OT[1] = s3;
  assign OT[2] = s5;
  assign OT[3] = s7;
  assign OT[4] = s9;
  assign OT[5] = s11;
  assign OT[6] = s13;
  assign OT[7] = s15;
  assign OT[8] = s17;
  assign OT[9] = s19;
  assign OT[10] = s21;
  assign OT[11] = s23;
  assign OT[12] = s25;
  assign OT[13] = s27;
  assign OT[14] = s29;
  assign OT[15] = s31;
endmodule

module ALU (
  input [2:0] OP,
  input [15:0] A,
  input [15:0] B,
  input Sub,
  output [15:0] O,
  output N,
  output C,
  output V,
  output Z
);
  wire [15:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  AND16 AND16_i0 (
    .A( A ),
    .B( B ),
    .O( s1 )
  );
  OR16 OR16_i1 (
    .A( A ),
    .B( B ),
    .O( s2 )
  );
  XOR16 XOR16_i2 (
    .A( A ),
    .B( B ),
    .O( s3 )
  );
  NOT16 NOT16_i3 (
    .A( A ),
    .O( s4 )
  );
  Full_add_sub Full_add_sub_i4 (
    .Cin( Sub ),
    .A( A ),
    .B( B ),
    .S( s0 ),
    .N( N ),
    .C( C ),
    .V( V ),
    .Z( Z )
  );
  \16bit_8_to_1_MUX  \16bit_8_to_1_MUX_i5 (
    .OP( OP ),
    .AD( 16'b0 ),
    .SB( s0 ),
    .ND( s1 ),
    .\OR ( s2 ),
    .XR( s3 ),
    .NT( s4 ),
    .SP( 16'b0 ),
    .SP2( 16'b0 ),
    .OT( O )
  );
endmodule

module DIG_Register
(
    input C,
    input en,
    input D,
    output Q
);

    reg  state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module flags (
  input N,
  input C,
  input V,
  input Z,
  input FlagWrite,
  input CLK,
  output Zf,
  output Nf,
  output Cf,
  output Vf
);
  DIG_Register DIG_Register_i0 (
    .D( Z ),
    .C( CLK ),
    .en( FlagWrite ),
    .Q( Zf )
  );
  DIG_Register DIG_Register_i1 (
    .D( N ),
    .C( CLK ),
    .en( FlagWrite ),
    .Q( Nf )
  );
  DIG_Register DIG_Register_i2 (
    .D( C ),
    .C( CLK ),
    .en( FlagWrite ),
    .Q( Cf )
  );
  DIG_Register DIG_Register_i3 (
    .D( V ),
    .C( CLK ),
    .en( FlagWrite ),
    .Q( Vf )
  );
endmodule

module immediate (
  input [3:0] RA,
  input [3:0] RB,
  input [15:0] RDval,
  output [15:0] IMM,
  output [15:0] LUI
);
  wire [7:0] s0;
  assign s0[3:0] = RB;
  assign s0[7:4] = RA;
  assign IMM[7:0] = s0;
  assign IMM[15:8] = 8'b0;
  assign LUI[7:0] = RDval[7:0];
  assign LUI[15:8] = s0;
endmodule

module writeback (
  input [15:0] ALU,
  input [15:0] MEM,
  input [15:0] IMM,
  input [15:0] LUI,
  input [1:0] WBsrc,
  output [15:0] WBdata
);
  wire s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire s3;
  assign s0 = WBsrc[0];
  assign s3 = WBsrc[1];
  // MUXA
  \16bit2_to_1MUX  \16bit2_to_1MUX_i0 (
    .A( ALU ),
    .B( MEM ),
    .S( s0 ),
    .O( s1 )
  );
  // MUXB
  \16bit2_to_1MUX  \16bit2_to_1MUX_i1 (
    .A( IMM ),
    .B( LUI ),
    .S( s0 ),
    .O( s2 )
  );
  // MUXF
  \16bit2_to_1MUX  \16bit2_to_1MUX_i2 (
    .A( s1 ),
    .B( s2 ),
    .S( s3 ),
    .O( WBdata )
  );
endmodule
module DIG_RegisterFile
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
    input [(Bits-1):0] Din,
    input we,
    input [(AddrBits-1):0] Rw,
    input C,
    input [(AddrBits-1):0] Ra,
    input [(AddrBits-1):0] Rb,
    output [(Bits-1):0] Da,
    output [(Bits-1):0] Db
);

    reg [(Bits-1):0] memory[0:((1 << AddrBits)-1)];

    assign Da = memory[Ra];
    assign Db = memory[Rb];

    always @ (posedge C) begin
        if (we)
            memory[Rw] <= Din;
    end
endmodule


module branch (
  input [1:0] Cond,
  input Zf,
  input Nf,
  input Vf,
  input Branch,
  output JumpEn
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  \NOT  \NOT_i0 (
    .A( Zf ),
    .O( s2 )
  );
  \XOR  \XOR_i1 (
    .A( Nf ),
    .B( Vf ),
    .O( s5 )
  );
  assign s0 = Cond[0];
  assign s1 = Cond[1];
  \NOT  \NOT_i2 (
    .A( s5 ),
    .O( s6 )
  );
  \AND  \AND_i3 (
    .A( s2 ),
    .B( s6 ),
    .O( s3 )
  );
  \4_to_1_MUX  \4_to_1_MUX_i4 (
    .S1( s0 ),
    .S2( s1 ),
    .A1( 1'b1 ),
    .B1( Zf ),
    .A2( s2 ),
    .B2( s3 ),
    .O( s4 )
  );
  \AND  \AND_i5 (
    .A( s4 ),
    .B( Branch ),
    .O( JumpEn )
  );
endmodule
module DIG_RAMDualAccess
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
    input C, // Clock signal
    input ld,
    input [(AddrBits-1):0] \1A ,
    input [(AddrBits-1):0] \2A ,
    input [(Bits-1):0] \1Din ,
    input str,
    output [(Bits-1):0] \1D ,
    output [(Bits-1):0] \2D
);
    // CAUTION: uses distributed RAM
    reg [(Bits-1):0] memory [0:((1 << AddrBits)-1)];

    assign \1D = ld? memory[\1A ] : 'hz;
    assign \2D = memory[\2A ];

    always @ (posedge C) begin
        if (str)
            memory[\1A ] <= \1Din ;
    end

endmodule



module CPU_export (
  input R,
  input clock
);
  wire s0;
  wire [15:0] s1;
  wire s2;
  wire s3;
  wire [15:0] s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire [3:0] s7;
  wire [3:0] s8;
  wire [15:0] s9;
  wire [12:0] s10;
  wire s11;
  wire [2:0] s12;
  wire s13;
  wire [1:0] s14;
  wire s15;
  wire s16;
  wire [1:0] s17;
  wire s18;
  wire s19;
  wire [15:0] s20;
  wire [15:0] s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire [15:0] s29;
  wire [15:0] s30;
  wire [15:0] s31;
  wire [15:0] s32;
  wire s33;
  wire [3:0] s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( 1'b1 ),
    .C( clock ),
    .Q( s38 )
  );
  \NOT  \NOT_i1 (
    .A( clock ),
    .O( s39 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s38 ),
    .C( s39 ),
    .\~Q ( s37 )
  );
  \OR  \OR_i3 (
    .A( s37 ),
    .B( R ),
    .O( s0 )
  );
  Instruction_reader Instruction_reader_i4 (
    .R( s0 ),
    .clk( clock ),
    .JMP_ADDR( s1 ),
    .JMPE( s2 ),
    .WE( s3 ),
    .Data_in( 1'b0 ),
    .STR( 1'b0 ),
    .STR_ADDR( 1'b0 ),
    .INSTR_IN( s4 ),
    .OP( s5 ),
    .RA( s6 ),
    .RB( s7 ),
    .RD( s8 ),
    .PC_OUT( s9 )
  );
  control control_i5 (
    .OP( s5 ),
    .OUT( s10 )
  );
  assign s11 = s10[0];
  assign s12 = s10[3:1];
  assign s13 = s10[4];
  assign s14 = s10[6:5];
  assign s15 = s10[7];
  assign s16 = s10[8];
  assign s17 = s10[10:9];
  assign s18 = s10[11];
  assign s19 = s10[12];
  \NOT  \NOT_i6 (
    .A( s19 ),
    .O( s3 )
  );
  assign s35 = s14[0];
  assign s36 = s14[1];
  \AND  \AND_i7 (
    .A( s35 ),
    .B( s36 ),
    .O( s33 )
  );
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i8 (
    .sel( s33 ),
    .in_0( s6 ),
    .in_1( s8 ),
    .out( s34 )
  );
  ALU ALU_i9 (
    .OP( s12 ),
    .A( s1 ),
    .B( s20 ),
    .Sub( s13 ),
    .O( s21 ),
    .N( s22 ),
    .C( s23 ),
    .V( s24 ),
    .Z( s25 )
  );
  flags flags_i10 (
    .N( s22 ),
    .C( s23 ),
    .V( s24 ),
    .Z( s25 ),
    .FlagWrite( s18 ),
    .CLK( clock ),
    .Zf( s26 ),
    .Nf( s27 ),
    .Vf( s28 )
  );
  immediate immediate_i11 (
    .RA( s6 ),
    .RB( s7 ),
    .RDval( s1 ),
    .IMM( s29 ),
    .LUI( s30 )
  );
  writeback writeback_i12 (
    .ALU( s21 ),
    .MEM( s31 ),
    .IMM( s29 ),
    .LUI( s30 ),
    .WBsrc( s14 ),
    .WBdata( s32 )
  );
  DIG_RegisterFile #(
    .Bits(16),
    .AddrBits(4)
  )
  DIG_RegisterFile_i13 (
    .Din( s32 ),
    .we( s11 ),
    .Rw( s8 ),
    .C( clock ),
    .Ra( s34 ),
    .Rb( s7 ),
    .Da( s1 ),
    .Db( s20 )
  );
  branch branch_i14 (
    .Cond( s17 ),
    .Zf( s26 ),
    .Nf( s27 ),
    .Vf( s28 ),
    .Branch( s16 ),
    .JumpEn( s2 )
  );
  DIG_RAMDualAccess #(
    .Bits(16),
    .AddrBits(16)
  )
  DIG_RAMDualAccess_i15 (
    .str( s15 ),
    .C( clock ),
    .ld( 1'b1 ),
    .\1A ( s1 ),
    .\1Din ( s20 ),
    .\2A ( s9 ),
    .\1D ( s31 ),
    .\2D ( s4 )
  );
endmodule
